# Generated by Django 4.2.20 on 2025-05-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleUser',
        ),
    ]
