# Generated by Django 4.2.20 on 2025-05-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinvite',
            name='is_used',
        ),
    ]
