# Generated by Django 4.2.20 on 2025-05-25 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_column_is_system_alter_column_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('from_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cards.column')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cards.column')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='work_item.workitem')),
            ],
        ),
    ]
