# Generated by Django 4.2.20 on 2025-05-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
